### ISSUE TITLE
Run specs like a charm + add travis-ci

### ISSUE THREAD

**Issue by rngtng** [priithaamer/adyen-skinbuilder#9]
I couldn't get the tests running - expected `rake spec` or `rspec spec/lib/adyen-skinbuilder/server_spec.rb` didn't work. 

```
  `require': no such file to load -- rack/test (LoadError)
```

... and in addition a travis-ci hook would be double-rainbow! :-)

**Comment by priithaamer** [comment]
Fixed.

**Comment by rngtng** [comment]
Awsm thx!

On 23.03.2012, at 09:56, Priit Haamer
reply@reply.github.com
wrote:
